### ISSUE TITLE
Path Download

### ISSUE THREAD

**Issue by CNB-DarksGol** [Girbons/comics-downloader#101]
Hi, I'm doing a project that would need to download the images, but I didn't quite understand the path you used to download them, could you inform me and/or help me?

**Comment by Girbons** [comment]
Hi @CNB-DarksGol, 

by default the path used is `comics/[source]/[name]/images-[(chapter/issue)-number]` but you can play with more options to customize the path, take a look at the readme.

if you have more questions reach me out on discord Girbons#7233
