### ISSUE TITLE
readcomiconline.il not working

### ISSUE THREAD

**Issue by Getty-13** [Girbons/comics-downloader#110]
**Describe the bug**
Any links from https://readcomiconline.li come back as "No Issues Found"

If I enter the URL for a specific issue for readcomiconline.li it saves a pdf less than 1mb in less than a second that is blank.

**To Reproduce**
Steps to reproduce the behavior: putting any links from readcomiconline.li in the url string

![image](https://user-images.githubusercontent.com/55208935/163348403-55546b90-bcfc-4d79-9048-0f7c5e04ed33.png)

![image](https://user-images.githubusercontent.com/55208935/163348229-c88579fb-bfb3-4f50-a046-61a0bc99f919.png)

**Comment by Girbons** [comment]
Hey @Getty-13, 

reacomiconline has introduced cloudflare as ddos protection a couple of months ago I think, another user have reported this issue, sadly I don't have a workaround yet

**Comment by igorrates** [comment]
Maybe we can try changing the support to the Russian domain... it should work since the website is pretty much the same
https://readcomicsonline.ru/

**Comment by Girbons** [comment]
Thank you for the suggestion @igorrates!

 If it is just a domain change it should be a straightforward change, by the end of the week I'll try to plan a new release.
By the way if you want feel free to submit PR 😄

**Comment by igorrates** [comment]
I'm planning to get the project set up and running on my machine, but I know nothing about the Go language. I have always been a dotnet / JavaScript developer. I need to learn Go 😀 so I can start supporting the project. 

As soon as I get this running and able to test locally I'll submit a PR. 😉

**Comment by StrangeDOS** [comment]
Just adding that I'm also wanting to use the readcomiconline.il or readcomiconline.ru site and can't.

**Comment by ObiSandwich** [comment]
Is there any news on this one please? I've had a break from comics for a few months and just found out readcomiconline.il not working :(

**Comment by Girbons** [comment]
Sorry but currently I can't provide any fix, hopefully, in 2/3 weeks I'm going to work again on this project.
