### ISSUE TITLE
MangaTown is no longer working

### ISSUE THREAD

**Issue by futurevessel** [Girbons/comics-downloader#111]
comics-downloader -format cbz -url chapter

returns: [0s:0s]ERRO[0001] image: unknown format

edit: mangakakalot & manganato seem to have the same problem

**Comment by Girbons** [comment]
Hey @futurevessel thanks for the report, I'm gong to tackle it in the next few days!

**Comment by jestraw** [comment]
Debug log isn't particularly revealing:

`$ comics-downloader -debug -images-only -url 'http://www.mangatown.com/manga/chihayafuru/c244/'
INFO[0000] Downloading...                               
DEBU[0017] Image Links found: https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s001.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s002.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s003.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s004.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s005.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s006.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s007.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s008.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s009.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s010.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s011.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s012.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s013.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s014.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s015.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s016.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s017.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s018.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s019.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s020.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s021.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s022.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s023.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s024.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s025.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s026.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s027.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s028.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s029.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s030.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s031.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s032.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s033.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s034.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s035.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s036.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s037.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s038.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s039.jpg https://zjcdn.mangahere.org/store/manga/6624/244.0/compressed/s040.jpg 
   0% |                                        |  [0s:0s]ERRO[0017] image: unknown format`

For what it's worth, after this error, the comic directory is filled with a set of 0-size image files.

**Comment by Girbons** [comment]
Might be related to -> https://github.com/Girbons/comics-downloader/commit/85bc2a676a31c7bb3b6c2bcdd0c000606102af16#r70352440

I'm going to release an alpha with this patch, please let me know if it works 🙏

**Comment by Girbons** [comment]
@futurevessel @jestraw could you please try it out https://github.com/Girbons/comics-downloader/releases/tag/v0.33.1-alpha ?

**Comment by futurevessel** [comment]
Yep, tried downloading from all three sites and everything seems to work fine, thanks!

**Comment by Girbons** [comment]
Thank you guys 😄
