### ISSUE TITLE
One failed issue creates strange subfolders

### ISSUE THREAD

**Issue by MattiasStorm** [Girbons/comics-downloader#112]
**Describe the bug**
I downloaded Sonic the Hedgehog from comicextra. I tried to download all issues and when it hit issue 258 it threw the "image: unknown format" error. Looking at that specific issue shows that the images are broken, so it is not due to Comics Downloader. However, after it failed that issue, Comics Downloader started making a subfolder inside the failed issue to download the rest of the comics.

The first downloads went to
`C:\Users\USER\Desktop\CBDL\comics\www.comicextra.com\sonic-the-hedgehog-1993\`
the following downloads went to
`C:\Users\USER\Desktop\CBDL\comics\www.comicextra.com\sonic-the-hedgehog-1993\images-chapter-258\comics\www.comicextra.com\sonic-the-hedgehog-1993`

**To Reproduce**
Run the command:
`comics-downloader.exe -format=cbz -url=https://www.comicextra.com/comic/sonic-the-hedgehog-1993`

**Expected behavior**
Once issue 258 failed, it should keep downloading to the same folder, not create a new subfolder from within the failed issue.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: v0.33.1
 - Type: command line

**Additional context**
To clarify: the download failed not because of Comics Downloader, that is a fault of comicextra, but the problem is that extra subfolders are created in case one of many downloads fail.

**Comment by MattiasStorm** [comment]
Had the same problem again, this time with a comic where 4 issues had problems with the image format:
![image](https://user-images.githubusercontent.com/29437966/168875536-e09dd49f-bc5b-4dde-9f3a-472b063c9966.png)

```
comics-downloader.exe -all -format=cbz -url=https://www.comicextra.com/comic/kim-reaper-vampire-island
time="2022-05-17T19:32:47+02:00" level=info msg=Downloading...
   0% |                                        |  [0s:0s]time="2022-05-17T19:32:50+02:00" level=error msg="image: unknown format"
   0% |                                        |  [0s:0s]time="2022-05-17T19:32:50+02:00" level=error msg="image: unknown format"
   0% |                                        |  [0s:0s]time="2022-05-17T19:32:51+02:00" level=error msg="image: unknown format"
   0% |                                        |  [0s:0s]time="2022-05-17T19:32:52+02:00" level=error msg="image: unknown format"
```

**Comment by Girbons** [comment]
Hi @MattiasStorm!

Thanks for reporting this issue, indeed it is really weird that it creates this nesting when an image download fail, I'm going to provide a fix for this weekend!
