### ISSUE TITLE
Can't use flag -all on readallcomics.com

### ISSUE THREAD

**Issue by igorrates** [Girbons/comics-downloader#113]
**Describe the bug**
I'm trying to download all issues at once from readallcomics.com and is throwing an exception running from mac terminal.

**To Reproduce**
` ./comics-downloader-osx -url=http://readallcomics.com/category/spider-manred-sonja/ -all -format=cbr `

` INFO[0000] Downloading... `                              
`panic: runtime error: invalid memory address or nil pointer dereference`
`[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1351e8c]`

`goroutine 1 [running]:`
`github.com/anaskhan96/soup.findAllofem.func1(0x18?, {0xc000254670?, 0x1, 0x1}, 0x80?)`
`	/Users/girbons/go/pkg/mod/github.com/anaskhan96/soup@v1.2.4/soup.go:534 +0x1cc`
`github.com/anaskhan96/soup.findAllofem(0xc0000d5900?, {0xc000254670, 0x1, 0x1}, 0x0)`
`	/Users/girbons/go/pkg/mod/github.com/anaskhan96/soup@v1.2.4/soup.go:538 +0xe4`
`github.com/anaskhan96/soup.Root.FindAll({0x0, {0x0, 0x0}, {0x14e74e0, 0xc00000e018}}, {0xc000254670?, 0x1, 0x1})`
`	/Users/girbons/go/pkg/mod/github.com/anaskhan96/soup@v1.2.4/soup.go:283 +0x86`
`github.com/Girbons/comics-downloader/pkg/sites.(*Readallcomics).isSingleIssue(0xc00048ba98?, {0x205aefa15?,0xc0004fbb90?})`
`	/Users/girbons/go/src/github.com/Girbons/comics-downloader/pkg/sites/readallcomics.go:55 +0x1d8`
`github.com/Girbons/comics-downloader/pkg/sites.(*Readallcomics).RetrieveIssueLinks(0xc00048be08?)`
`	/Users/girbons/go/src/github.com/Girbons/comics-downloader/pkg/sites/readallcomics.go:78 +0x5a`
`github.com/Girbons/comics-downloader/pkg/sites.LoadComicFromSource(0xc0000ec8f0)`
`	/Users/girbons/go/src/github.com/Girbons/comics-downloader/pkg/sites/loader.go:118 +0x3d2`
`github.com/Girbons/comics-downloader/cmd/app.download(0xc0000ec8f0)`
`	/Users/girbons/go/src/github.com/Girbons/comics-downloader/cmd/app/downloader.go:78 +0x312`
`github.com/Girbons/comics-downloader/cmd/app.Run(0xc0000ec8f0)`
`	/Users/girbons/go/src/github.com/Girbons/comics-downloader/cmd/app/downloader.go:125 +0x1c9`
`main.main()`
`	/Users/girbons/go/src/github.com/Girbons/comics-downloader/cmd/downloader/main.go:93 +0x26a `

**Expected behavior**
The issues are downloaded correctly 

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Version v12.4

**Additional context**
I gave all the permissions for the binary using `chmod 755`

**Comment by Girbons** [comment]
Hi @igorrates, thanks for reporting this issue!

 seems like that the scraper logic needs an update, I will take a look asap!

**Comment by Girbons** [comment]
I can't provide a fix, readallcomics is broken
