### ISSUE TITLE
Low image resolution output

### ISSUE THREAD

**Issue by ObiSandwich** [Girbons/comics-downloader#115]
Linux LMDE4
v0.33.2 CLI

I am new here and thank you for creating this very clever script - I prefer uncompressed and higher resolution images to help reading when zooming-in. So not sure if I am missing something, but the default "image only" and "cbz" output is a lower image resolution than the source. Is there a way to download the higher/original image resolution please? Is there a High/Max Quality argument?

**Example**

This outputs the lower resolution = 1041 x 1600 px
`./comics-downloader -url=https://www.comicextra.com/comic/bob-s-burgers-2014 -images-only -images-format=png`

Image link source (issue 1, page 3) = 1988 x 3056 px
`https://2.bp.blogspot.com/q4TI829d1r9gh5btOBJAhY6o3SlagZPbl26_JPM0MmBTke7JPABitZI-WEDmCkuGvYbRIhBTNTt8=s0`

**Comment by Girbons** [comment]
Right now there isn't an argument to decide the image resolution, but I will plan some work on it

**Comment by ObiSandwich** [comment]
Great! Thank you very much :)
