### ISSUE TITLE
readcomiconline.li not happy

### ISSUE THREAD

**Issue by ObiSandwich** [Girbons/comics-downloader#117]
OS: Linux LMDE4
v0.33.3 

Strugling to get script working with: **readcomiconline.li** - But I have been able to get it to work with: **comicextra.com** and **readallcomics.com** The reason I want it to work with **readcomiconline.li** is because there are some comics on there that are not available elsewhere.

Running the command below, just gives me empty and corrupt cbz files. Please could you let me know if this is the correct command for **readcomiconline.li** ?

**TEST**
`./comics-downloader -all -format=cbz -url=https://readcomiconline.li/Comic/Bob-s-Burgers-2014`

![Screenshot from 2022-08-20 23-45-31-2](https://user-images.githubusercontent.com/41534480/185768636-8e53702c-2901-463e-b409-1407761cd248.png)

![Screenshot from 2022-08-20 23-58-56](https://user-images.githubusercontent.com/41534480/185768803-1cb394ea-bdbb-4cf8-ad4e-0c3cf8c68fee.png)

**Comment by Girbons** [comment]
Following the issue #110 Have you tried using the ".ru" domain? Because if I remember correctly readcomiconline.li has cloudflare has ddos protection

**Comment by ObiSandwich** [comment]
Yep, I get...

```
INFO[0000] Downloading...                               
ERRO[0000] source unknown  
```
(test comic above not available on .ru so tried this one instead)

`./comics-downloader -all -format=cbz -url=https://readcomicsonline.ru/comic/bobs-burgers-2015`

Also tried the following with the same error;

`./comics-downloader -all -format=cbz -url=https://readcomicsonline.ru/comic/spiderman-legends-todd-mcfarlane-20032004`

Was **readcomiconline.ru** added to v0.33.3 ?

**Comment by Girbons** [comment]
> Was readcomiconline.ru added to v0.33.3 ?

I did a quick check and realized that it was partly added, I will ship a fix soon for that!

**Comment by ObiSandwich** [comment]
Thank you. There is a subtle difference in the two website addresses and I'm not sure if they are the same people behind the sites - don't forget the 's' in: readcomicsonline.ru :)

**Comment by Girbons** [comment]
@ObiSandwich  here's a [pre-release](https://github.com/Girbons/comics-downloader/releases/tag/v0.33.4-alpha) with a possible fix, could you please try it out? I'm also planning to add a check that logs if the captcha appears

**Comment by ObiSandwich** [comment]
Thanks, but same outcome I'm afraid.

Got lots of different text below the command this time around and ended up with the error below;

`./comics-downloader -all -format=cbz -url=https://readcomiconline.li/Comic/Spider-Man-1990`

```
(function() { (window.adblockDetector = window.adblockDetector || []).push(function() { window.adbDetector.init({ id: 'e3e09e6b5c1c6f8fce95004450468f13', debug: true, cookieExpire: 10, found: function() { window.adbDetector.alert({ hiddenCloseButton: false, clickBackgroundToClose: false }); } }); }) } ()); </script>
<script>(function(){var js = "window['__CF$cv$params']={r:'73e60bdbecaf8e15',m:'tmtZ1XGWZtap2Es9SzP5T5hDyw6B0Vvj78UYRnNRT7o-1661112985-0-ATCVqPE3ZC6J/ccSo31U84S1dTZNKMMxXLsA5VH6MHjg6IOJNfjhSP6fZNeasorQRxsJF3pTeQ3bMe1JfPzHWovp6M1q2911pRTYnkGMDNW3pSDGKXTMR4ZkUxw7BxpUWAjVvujUXPZiKuUmKQLorn3fT9NfUSdF084cApLR4Lzq1Sfi8O+Vcn24madJqyHRSUg/asFZ/AaSYGQa12UdvsMhJoji5oaphyQEfKEHnRmA',s:[0x9c8a79b0c1,0x414b83e9bf],u:'/cdn-cgi/challenge-platform/h/g'};var now=Date.now()/1000,offset=14400,ts=''+(Math.floor(now)-Math.floor(now%offset)),_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/h/g/scripts/alpha/invisible.js?ts='+ts,document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.nonce = '';_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script></body>
</html>

   0% |                                        |  [0s:0s]ERRO[0079] There was an error while downloading image number: 7 - comic issue: 98-The-Final-Chapter-4-of-4 
   4% |█                                       |  [0s:22s]ERRO[0079] There was an error while downloading image number: 4 - comic issue: 98-The-Final-Chapter-4-of-4 
   8% |███                                     |  [0s:21s]ERRO[0079] There was an error while downloading image number: 3 - comic issue: 98-The-Final-Chapter-4-of-4 
  12% |█████                                   |  [0s:20s]ERRO[0079] There was an error while downloading image number: 1 - comic issue: 98-The-Final-Chapter-4-of-4 
  16% |██████                                  |  [0s:19s]ERRO[0080] There was an error while downloading image number: 6 - comic issue: 98-The-Final-Chapter-4-of-4 
  20% |████████                                |  [0s:18s]ERRO[0080] There was an error while downloading image number: 2 - comic issue: 98-The-Final-Chapter-4-of-4 
  25% |██████████                              |  [0s:17s]ERRO[0080] There was an error while downloading image number: 5 - comic issue: 98-The-Final-Chapter-4-of-4 
  29% |███████████                             |  [0s:16s]ERRO[0080] There was an error while downloading image number: 0 - comic issue: 98-The-Final-Chapter-4-of-4 
  33% |█████████████                           |  [0s:15s]ERRO[0080] There was an error while downloading image number: 8 - comic issue: 98-The-Final-Chapter-4-of-4 
  37% |███████████████                         |  [1s:14s]ERRO[0080] There was an error while downloading image number: 9 - comic issue: 98-The-Final-Chapter-4-of-4 
  41% |████████████████                        |  [1s:13s]ERRO[0080] There was an error while downloading image number: 10 - comic issue: 98-The-Final-Chapter-4-of-4 
  45% |██████████████████                      |  [1s:12s]ERRO[0080] There was an error while downloading image number: 13 - comic issue: 98-The-Final-Chapter-4-of-4 
  50% |████████████████████                    |  [1s:11s]ERRO[0080] There was an error while downloading image number: 12 - comic issue: 98-The-Final-Chapter-4-of-4 
  54% |█████████████████████                   |  [1s:10s]ERRO[0080] There was an error while downloading image number: 11 - comic issue: 98-The-Final-Chapter-4-of-4 
  58% |███████████████████████                 |  [1s:9s]ERRO[0080] There was an error while downloading image number: 14 - comic issue: 98-The-Final-Chapter-4-of-4 
  62% |█████████████████████████               |  [1s:8s]ERRO[0080] There was an error while downloading image number: 15 - comic issue: 98-The-Final-Chapter-4-of-4 
  66% |██████████████████████████              |  [1s:7s]ERRO[0080] There was an error while downloading image number: 16 - comic issue: 98-The-Final-Chapter-4-of-4 
  70% |████████████████████████████            |  [1s:6s]ERRO[0080] There was an error while downloading image number: 17 - comic issue: 98-The-Final-Chapter-4-of-4 
  75% |██████████████████████████████          |  [1s:5s]ERRO[0080] There was an error while downloading image number: 20 - comic issue: 98-The-Final-Chapter-4-of-4 
  79% |███████████████████████████████         |  [1s:4s]ERRO[0080] There was an error while downloading image number: 19 - comic issue: 98-The-Final-Chapter-4-of-4 
  83% |█████████████████████████████████       |  [1s:3s]ERRO[0080] There was an error while downloading image number: 21 - comic issue: 98-The-Final-Chapter-4-of-4 
  87% |███████████████████████████████████     |  [1s:2s]ERRO[0080] There was an error while downloading image number: 18 - comic issue: 98-The-Final-Chapter-4-of-4 
  91% |████████████████████████████████████    |  [1s:1s]ERRO[0080] There was an error while downloading image number: 23 - comic issue: 98-The-Final-Chapter-4-of-4 
  95% |██████████████████████████████████████  |  [1s:0s]ERRO[0080] There was an error while downloading image number: 22 - comic issue: 98-The-Final-Chapter-4-of-4 
 100% |████████████████████████████████████████|  [1s:0s]INFO[0080] CBZ file correctly saved                     
   0% |                                        |  [0s:0s]ERRO[0080] There was an error while downloading image number: 1 - comic issue: 97 
   4% |█                                       |  [0s:0s]ERRO[0080] There was an error while downloading image number: 0 - comic issue: 97 
   8% |███                                     |  [0s:0s]ERRO[0080] There was an error while downloading image number: 4 - comic issue: 97 
```


Also tried a **readcomicsonline.ru** test;

`./comics-downloader -all -format=cbz -url=./comics-downloader -all -format=cbz -url=https://readcomicsonline.ru/comic/bobs-burgers-2015`

> INFO[0000] Downloading...                               
> ERRO[0000] No issues found 

Not sure if this helps in any way, but I used to use the following script before it stopped working, this script also included a way around the **readcomiconline.li** captcha, so not sure if this would be of any help to you? 

It is an abandoned project now, so not sure why theirs stopped working.

https://github.com/team-hunting/ComicDownloader

**Comment by Girbons** [comment]
> Got lots of different text below the command this time around and ended up with the error below;

Really sorry, I left some debugging print text 😄 

> Not sure if this helps in any way, but I used to use the following script before it stopped working, this script also included a way around the readcomiconline.li captcha, so not sure if this would be of any help to you?

In the next days I will investigate if there's something that allows the captcha bypass

**Comment by Girbons** [comment]
Sorry for being late, I didn't find something that could solve this issue yet. 
If I have time this weekend I'll try to see if there's a possible workaround that could be used

**Comment by LegalizeAdulthood** [comment]
OK this may sound like a completely dumb idea, but it's a very different approach from what has been tried already....

what about writing an http proxy that sits between the browser and the remote site that just dumps any images requested by the browser and drive the browser with a GUI automation tool like [AutoIt on Windows](https://www.autoitscript.com/site/)?

**Comment by Girbons** [comment]
@LegalizeAdulthood this is an interesting idea! 

The problem is that currently I dont have the time to implement this solution

**Comment by tabletseeker** [comment]
Use this, the only working readcomiconline downloaded in 2024: https://github.com/tabletseeker/readcomic_dl
