### ISSUE TITLE
Files saved at 1kb

### ISSUE THREAD

**Issue by StrangeDOS** [Girbons/comics-downloader#123]
**Describe the bug**
All files created are just empty 1kb files.  

**To Reproduce**
comics-downloader -url=https://readcomiconline.li/Comic/52

**Expected behavior**
Expected pdf files to actually have content

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version [Alpha]
 - Type [CLI]

**Additional context**

**Comment by ObiSandwich** [comment]
See: https://github.com/Girbons/comics-downloader/issues/117

**Comment by Girbons** [comment]
closing as this is a duplicate as pointed out by @ObiSandwich

**Comment by Girbons** [comment]
I just find out that the previous logic to get the images was not working at all, so this is different from #117 😄
