### ISSUE TITLE
Comic Extra not supported any more!

### ISSUE THREAD

**Issue by ObiSandwich** [Girbons/comics-downloader#125]
**Describe the bug**

Something has changed at Comic Extra and the script doesn't seem to be working with this site at the moment.

**To Reproduce**

```
./comics-downloader -all -format=cbz -url=https://ww1.comicextra.com/comic/eight-billion-genies
ERRO[0000] This site is not supported  
```

**Desktop (please complete the following information):**
 - OS: Linux LMDE4
 - Version: v0.33.3 and v0.33.4 Alpha
 - Type: CLI

**Comment by Girbons** [comment]
this should be fixed by #122
