### ISSUE TITLE
[Question][Possible bug] Where are the files stored?

### ISSUE THREAD

**Issue by Galunid** [Girbons/comics-downloader#13]
Hi, I have the following problem:
```
./Downloads/comics-downloader -format cbz -url https://mangarock.com/manga/mrs-serie-162959/chapter/mrs-chapter-162962
```
This is the command I used to test this application. It proceeds to download the chapter, but the chapter is nowhere to be seen, after it finishes its execution. Application has necessary privileges. I did a 
`find -name *.cbz`, but it failed to find anything. Same happens with pdfs. Also is there an option to download whole manga and not a single chapter? Thanks for your contribution to this project!

**Comment by futurevessel** [comment]
Can confirm this on Linux, the last version I had was version 0.7 which placed the downloaded files in a directory called 'comics' in the path where you ran the command. I tried all the subsequent releases (0.7.1-0.9.2) and none of them created a directory nor did they store any downloaded files.

**Comment by Girbons** [comment]
Hey @Galunid and @futurevessel thanks for reporting!

Could you please try the version [0.9.3](https://github.com/Girbons/comics-downloader/releases/tag/v0.9.3) that should fix this issue.

@Galunid, the option to download the whole manga is not available yet.

**Comment by futurevessel** [comment]
Yep, 0.9.3 is working for me, thanks!

**Comment by Galunid** [comment]
@Girbons Yup, I can confirm it works. Creates new dir and puts downloaded file there. Are there any plans to add downloading whole comics?

**Comment by Girbons** [comment]
Thanks @futurevessel  @Galunid  🙏 

@Galunid Yes, but I don't know when it will be available.

**Comment by Girbons** [comment]
Hey @Galunid,

its now possible to download the whole comic!

**Comment by Galunid** [comment]
Damn, that's great! Thanks @Girbons
