### ISSUE TITLE
comicextra.net is deprecated but has new site

### ISSUE THREAD

**Issue by urmomstoaster** [Girbons/comics-downloader#131]
Site is deprecated & comicextra.net (new site) isn't supported when inputted

**Comment by Girbons** [comment]
Hi @urmomstoaster, thanks for the report! I'm going to ship a fix soon

**Comment by macninja** [comment]
The url has changed again.
It’s now just comicextra.net.
Would it be an option to have it maybe not look at the domain?

it works if I add the new URL to the detector and loader file before building.

although it will only download the first issue f any of the comics I tried.

**Comment by Girbons** [comment]
> Would it be an option to have it maybe not look at the domain?

I think that we can do that for comicextra

> although it will only download the first issue f any of the comics I tried.

Anyway I'm going to provide a fix even for that
