### ISSUE TITLE
Compiled for arm architecture,, not x86-64

### ISSUE THREAD

**Issue by filliphy** [Girbons/comics-downloader#132]
**Describe the bug**
Unable to run latest release of comics-downloader CLI on debian linux system

**To Reproduce**
Download from github - [comics-downloader](https://github.com/Girbons/comics-downloader/releases/download/v0.33.6/comics-downloader)
chmod +x comics-downloader
Run command: ./comics-downloader -url xxxxxx -format cbz

Error:
-bash: ./comics-downloader: cannot execute binary file: Exec format error

**Expected behavior**
software would download from expected site (readcomicsonline.li)

**Additional context**
if I run the command: **file comics-downloader**
comics-downloader: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=qckR0IQy0_jfLK6KTDJs/y44sxpxgAwXQh0MuVENZ/RUTfGhxzRHdOk58rv9fX/7EQasMKC7P2c8yCSgtpd, with debug_info, not stripped

Is there a x86-64 compiled version that I am not seeing?
Thank you for great software.

**Comment by Girbons** [comment]
Hi @filliphy,

try it out: [comics-downloader-linux-386](https://github.com/Girbons/comics-downloader/releases/download/v0.33.6/comics-downloader-linux-386)
