### ISSUE TITLE
readcomiconline.li issue

### ISSUE THREAD

**Issue by Frostbrewn** [Girbons/comics-downloader#134]
**Describe the bug**
Runtime error : Slice bounds out of range [ : -1]
This error happens for certain comic series that uses this blogspot link format of RCOn_w

**To Reproduce**
-url=https://readcomiconline.li/Comic/The-Amazing-Spider-Man-2018/Issue-1?id=136988#1

**Expected behavior**
Script functioning properly.

**Screenshots**
![image](https://github.com/Girbons/comics-downloader/assets/74014125/617e2218-ded8-4675-a0d0-c872b57b7848)
*Caption : Runtime error : Slice bounds out of range [ : -1]*

![image](https://github.com/Girbons/comics-downloader/assets/74014125/be0977f2-2e39-4bcb-86c6-dadabf9fd237)
*Caption : Suspected due to "RCOn_w" variance in URL parameter*

![image](https://github.com/Girbons/comics-downloader/assets/74014125/af02b001-1fe5-4f82-a25c-dcbbef9ee2d3)
*Caption : Appears on pages that has this edit*

![image](https://github.com/Girbons/comics-downloader/assets/74014125/61ef1e43-3697-4e3b-bb65-47d831bb8929)
*Caption : This issue can download as intended*

![image](https://github.com/Girbons/comics-downloader/assets/74014125/656c1a10-26cd-4f41-839b-c4739ab360bb)
*Caption : The usual URL that works for this domain*

![image](https://github.com/Girbons/comics-downloader/assets/74014125/f7eb3fc9-4c42-4690-a185-3ba8791d80e0)
*Caption : deobfuscateUrl()*
**Desktop (please complete the following information):**
 - OS : Windows 11
 - Version : 22H2
 - Type : CLI

**Additional context**
Also, I would like to understand in detail about the deobfuscateUrl() function. I hope that you will be willing to impart some knowledge to a beginner like me.

**Comment by Girbons** [comment]
Hi @Frostbrewn thanks for the report! 

> This error happens for certain comic series that uses this blogspot link format of RCOn_w

the fix should be pretty easy, we should get the url by replacing `_x236` and `_x945`

> Also, I would like to understand in detail about the deobfuscateUrl() function. I hope that you will be willing to impart some knowledge to a beginner like me.

it's just a string manipulation, I took that from readcomiconline
