### ISSUE TITLE
Mangareader changed top level domain

### ISSUE THREAD

**Issue by macninja** [Girbons/comics-downloader#135]
Mangareader changed the toplelev domain from .TV to .TO.

`% ./comics-downloader -all -format=cbz -output /comix -url=https://mangareader.to/sasaki-and-miyano-266
ERRO[0000] This site is not supported`

I tried to change the detector.go and mangareader.go sites files to reflect the new tld.
But after compile I got this output instead.

`% ./comics-downloader -all -format=cbz -output /comix -url=https://mangareader.to/sasaki-and-miyano-266
INFO[0000] Downloading...                               
ERRO[0000] source unknown `

**Comment by Girbons** [comment]
Thanks @macninja, I didn't noticed it today.

You should also change loader.go, which checks the source in order to load the right interface
