### ISSUE TITLE
This app can't run on your PC

### ISSUE THREAD

**Issue by JoshuaAdrian21** [Girbons/comics-downloader#137]
I downloaded the Windows exe but when I try to use any commands it says that the file is not a valid application for this OS. I have windows 10
![image](https://github.com/Girbons/comics-downloader/assets/143729410/1635405a-2f1c-42fb-b2da-9ce67b36cf37)

**Comment by JoshuaAdrian21** [comment]
I downloaded a an older version and it worked but the current version of the exe does not

**Comment by Evoley** [comment]
Which version did you download? I went back to .33.5 and I still couldn't get it to run

**Comment by Girbons** [comment]
@Evoley and @JoshuaAdrian21 please check the last comment [here](https://github.com/Girbons/comics-downloader/issues/138), it might solve the issue
