### ISSUE TITLE
Machine Type Mismatch

### ISSUE THREAD

**Issue by MatevzKu** [Girbons/comics-downloader#138]
**Describe the bug**
Upon running the newest version of the exe file in Windows I get a "Machine Type Mismatch" error and cannot do anything.

**To Reproduce**
Run comics-downloader.exe in any command prompt (tried on three different computers, Windows 10 and 11, same result)

**Expected behavior**
Comic downloading as usual :D

**Desktop (please complete the following information):**
 - OS: Windows 10 and 11
 - Version Latest (downloaded by link oon 11.9.2023)
 - Type command line version

**Comment by Girbons** [comment]
Hi @MatevzKu, 

thanks for the report!, I'll provide a fix soon

**Comment by Girbons** [comment]
@MatevzKu 

please try with the following
* [comics-downloader-win-386.exe](https://github.com/Girbons/comics-downloader/releases/download/v0.33.7/comics-downloader-win-386.exe)
* [comics-downloader-win-x86-64.exe](https://github.com/Girbons/comics-downloader/releases/download/v0.33.7/comics-downloader-win-x86-64.exe)

**Comment by MatevzKu** [comment]
It works, tried it with comicsextra.net and was able to get a comic down. Thanks for the fix!
