### ISSUE TITLE
chapmanganato issues erased

### ISSUE THREAD

**Issue by lfoosoodnfk** [Girbons/comics-downloader#142]
Hello! Great project! I really like it.

Since I started using it, I found two problems that occurs at least with chapmanganato. 

1) they changed their url to https://chapmanganato.to which occurs to the error "not supported". Could you remove these checks or add an option "-no-domain-check"?
2) if domain is changed to chapmanganato.com, the download occurs but the issues keep getting overwritten (e.g.: https://chapmanganato.com/manga-wd951838)

Thanks

**Comment by Girbons** [comment]
Hi @lfoosoodnfk thanks for the feedback! During the next weeks I'm going to address the points you mentioned

**Comment by lfoosoodnfk** [comment]
Thank you so much @Girbons ! I am looking forward to it 😁
