### ISSUE TITLE
Image download fails when format is WEBP

### ISSUE THREAD

**Issue by Ismail-Smile** [Girbons/comics-downloader#150]
**Describe the bug**
When attempting to download a manga chapter with pages in WEBP format (for example https://chapmanganato.to/manga-xl1000446/chapter-16) the download fails and comics-downloader outputs an empty .cbz file. For that particular manga, previous chapters that have pages in traditional formats like JPG and PNG download correctly.

**To Reproduce**

1. Run a comics-dowloader command like this:

    ./comics-downloader-linux-386 -url=https://chapmanganato.to/manga-xl1000446 -format=cbz -output=/home/user/Downloads/The\ Kouhai\ Who\ Went\ From\ Introvert\ To\ Influencer -range 16-16

**Expected behavior**
The downloaded CBZ file contains the images from the chapter.

**Screenshots**

![Captura de pantalla_20240514_150404](https://github.com/Girbons/comics-downloader/assets/166783501/7bb32f12-08eb-4000-8dbe-ebab9e440699)

**Desktop (please complete the following information):**
 - OS: headless Linux (Ubuntu Server 22.04)
 - Version: 0.33.9 
 - Type: CLI

**Comment by nbsmith** [comment]
Since there does not seem to be a good webp library out there for encoding/decoding, might I suggest when a webp is encountered that you simply save the webp as is. My workaround with webp has been opening the image in irfanview and using batch convert the entire folder to jpg. It's not elegant, but at least I can then zip the folders and using a zip image viewer to read the comics.

**Comment by nbsmith** [comment]
Fixed myself in a cludgy way in sure.
In core.go:

if strings.HasSuffix(link, ".webp") {
	err = util.SaveImageWEBP(imgFile, rsp.Body, format)
} else {
	err = util.SaveImage(imgFile, rsp.Body, format)
}
In image.go:
func SaveImageWEBP(w io.Writer, content io.Reader, format string) error {
	img, err := webp.Decode(content)

	if err != nil {
		return err
	}

	switch strings.ToLower(format) {
	case "img":
		_, err = io.Copy(w, content)
		return err
	case "gif":
		return gif.Encode(w, img, nil)
	case "jpg", "jpeg":
		return jpeg.Encode(w, img, &jpeg.Options{Quality: 100})
	case "png":
		pngEncoder := png.Encoder{CompressionLevel: png.BestCompression}
		return pngEncoder.Encode(w, img)
	default:
		return errors.New("format not found")
	}
}

**Comment by Girbons** [comment]
thanks @nbsmith for investigating and providing a solution, if you want feel free to submit a pull request otherwise I can do that in the next weeks. 

Sorry but have been busy months

**Comment by nbsmith** [comment]
If you think it's good enough, ill go ahead and do the pull request when I get home from work tonight.

**Comment by Girbons** [comment]
fixed by #155
