### ISSUE TITLE
Can not get it to run

### ISSUE THREAD

**Issue by ZeroCrossblade** [Girbons/comics-downloader#151]
when i click on the .exe file it do nothing

**Comment by ucapato** [comment]
Hi,

If you downloaded the cli version, just open a cmd windows, go to the directory where is was downloaded and type the file name. Like that (on this example I added parameter --help to check if it works):


<img width="880" alt="image" src="https://github.com/user-attachments/assets/c86baa48-41ec-42ed-8725-4111df1487d6">

**Comment by Girbons** [comment]
I'm going to close it as it is not an issue.
 if necessary, please move to discussion.
