### ISSUE TITLE
Version is not included in GUI

### ISSUE THREAD

**Issue by Girbons** [Girbons/comics-downloader#20]
The GUI version should display the latest version of the downloader.

**Comment by ilmanzo** [comment]
I guess you need to change the GUI build process, in order to be able to pass -ldflags option in the "go build" command ...

**Comment by Girbons** [comment]
I opened a PR for that https://github.com/lucor/fyne-cross/pull/2

**Comment by Girbons** [comment]
@ilmanzo are you gonna work on this?

**Comment by ilmanzo** [comment]
No, sorry but due to lack of free time currently I'm not working on this.

Il lun 20 mag 2019, 11:20 Alessandro De Angelis <notifications@github.com>
ha scritto:

**Comment by Girbons** [comment]
Ok, I'll take this.
