### ISSUE TITLE
If Fyne doesn't work out, Wails is a good option

### ISSUE THREAD

**Issue by trosel** [Girbons/comics-downloader#22]
https://wails.app/

It allows you to build the front end with html/css/javascript _without_ Electron.

You basically expose you `getManga` method to the front end and the javascript links into that with `backend.Manga.getManga()` or something.

**Comment by Girbons** [comment]
Thank you @trosel! I'll take that into consideration, I'll stick to fyne for now anyway since I'm also contributing to it. :)
