### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by ilmanzo** [Girbons/comics-downloader#23]
```
$ make linux-build

cmd/downloader/main.go:42:9: too many arguments in call to app.Run
	have (string, string, string, bool, bool)
	want (string, string, string, bool)
make: *** [Makefile:19: linux-build] Error 2
```

**Comment by Girbons** [comment]
Seems like you have on old version of `github.com/Girbons/comics-downloader/`.

Are you working on `github.com/Girbons/comics-downloader/` or in `github.com/ilmanzo/comics-downloader/`?

**Comment by ilmanzo** [comment]
yes, sorry my fault :)  I just had an old version in $GOROOT
