### ISSUE TITLE
Add option to check if chapter exists before downloading

### ISSUE THREAD

**Issue by SeNeO** [Girbons/comics-downloader#24]
First thanks for all the work on this project.

It could be usefull to add an option to check if the chapter doesn't exist in the download directory. It would allow user to use the `-all` option to download new chapter of the comic without re-downloading the previous ones.

**Comment by Girbons** [comment]
Hi @SeNeO thanks for the feedback 🙏 ,

Yes it is very helpful to add a check option for existent chapters 👍.

**Comment by Girbons** [comment]
Hi @SeNeO, 

This should be solved in v0.12.3.
