### ISSUE TITLE
not working on rapsberry pi

### ISSUE THREAD

**Issue by nestukh** [Girbons/comics-downloader#25]
in fact. it returns
`-sh: ./comics-downloader: cannot execute binary file: Exec format error`
I believe you've compiled the linux version for amd64, right? 

it would be nice having `comics-downloader` for standard raspian on a raspberry pi. Just with a daily cron script, a bit of bash/python & a syncthing folder, you can have manga issues delivered to your GUI device of choice automatically

Awesome program by the way

**Comment by Girbons** [comment]
Hi @nestukh thanks 🙏,

> I believe you've compiled the linux version for amd64, right?

Yes the linux version is compiled for amd64.

> it would be nice having comics-downloader for standard raspian on a raspberry pi. Just with a daily cron script, a bit of bash/python & a syncthing folder, you can have manga issues delivered to your GUI device of choice automatically

Nice idea 👍, could you please check if the [raspbian](https://github.com/Girbons/comics-downloader/releases/download/v0.12/comics-downloader-raspbian) version works?

**Comment by nestukh** [comment]
still getting
`-sh: ./comics-downloader-raspbian: cannot execute binary file: Exec format error`
I guess you'll need a raspberry pi zero w kit as dev platform, or an old raspi2 from ebay at least
It's not a priority, personally I can wait

**Comment by Girbons** [comment]
Try with [this](https://github.com/Girbons/comics-downloader/releases/download/v0.12/comics-downloader-raspbian-arm).

**Comment by nestukh** [comment]
it works, yes!
it's kind of heavy, ps reports as CPU usage 106% and as ram usage 15.3% (on a quadcore raspi3b), which is more than an instance of firefox-esr with selenium and python (CPU 29.8%, ram 32.0%)
anyway perfect, I'm closing this issue

**Comment by Girbons** [comment]
@nestukh one last question, are you using the PDF format right?

**Comment by nestukh** [comment]
yes

**Comment by Girbons** [comment]
Switching the format are the performance the same?

**Comment by nestukh** [comment]
epub
rise up to CPU 97.9  RAM 4.6 (starts at 88% CPU)

cbr
CPU 105  RAM 4.1

cbz
CPU 102  RAM 4.1


I'm using this oneliner
`./comics-downloader-raspbian-arm -url=https://mangarock.com/manga/mrs-serie-107406/chapter/mrs-chapter-107407 -format=cbz`

**Comment by Girbons** [comment]
I need to profile the downloader then.

thanks @nestukh!
