### ISSUE TITLE
example of bash script on a raspberry pi for checking mangas

### ISSUE THREAD

**Issue by nestukh** [Girbons/comics-downloader#27]
becasue github is stupid and there isn't a 'suggestion box and related stuff' for projects (outside source repos), or even private messages
so this is not a real issue, just an example for anyone interested, maybe to add to the wiki or whatever
completed with commented install instructions and general tips for raspbian
https://gist.github.com/nestukh/5397b836c8e5f34f6feb4ec4efe6b86a

**Comment by Girbons** [comment]
@nestukh thanks! 

 > becasue github is stupid and there isn't a 'suggestion box and related stuff' for projects

I can grant to you the permissions to write the wiki section if you'd like to 😄

**Comment by nestukh** [comment]
thank you I appreciate it, but that's not necessary
you can put a link to it or copypaste it

**Comment by Girbons** [comment]
Yes I will.

Eitherway I was thinking to introduce this functionality by default using the config file.

something like:
```
run_as_deamon: "true"
# seconds
run_every: "120"
mangas_to_check: [....]
```

@nestukh let me know what maybe could be useful

**Comment by nestukh** [comment]
I guess stuff on [the Board](https://github.com/Girbons/comics-downloader/projects/1#card-21327554) is enough
A deamon is probably good for people who use comics-dowloader directly on their pc/laptop, especially for not-that-much-tech-savvy people ([on average 70% of humans](https://jaxenter.com/wp-content/uploads/2016/11/Screen-Shot-2016-11-18-at-3.29.09-PM.png), but perhaps manga readers are a slightly better bunch)

**Comment by Girbons** [comment]
@nestukh thanks for the feedbacks,

Maybe before providing a deamon I need to reduce the overhead of the downloader, I should already have reduced resources utilization but I guess that's not enough yet.

**Comment by nestukh** [comment]
maybe is resource-intesive but that's ok, it isn't intended to real-time usage
