### ISSUE TITLE
Fails to download chapters which have a . in the name

### ISSUE THREAD

**Issue by ishands** [Girbons/comics-downloader#33]
```
Version: Comics Downloader Windows GUI v0.14
URL: https://mangarock.com/manga/mrs-serie-100399051
Output: PDF
```

I faced an issue while trying to download Chapter 13.5
1. It was saved without a .pdf extension
2. It was 0 bytes in size
3. Other chapters all downloaded fine

**Comment by Girbons** [comment]
Hey @ishands,

thanks for reporting, a fix is available in the [new version](https://github.com/Girbons/comics-downloader/releases/tag/v0.14.1)
