### ISSUE TITLE
Download comic as images inside respective folders

### ISSUE THREAD

**Issue by satishbabariya** [Girbons/comics-downloader#34]
Download comic as images inside respective folders like **mangarock.com/naruto/cp-01/1.img** ...

**Comment by Girbons** [comment]
Hi @satishbabariya,

Basically, you are asking to keep the downloaded images alongside the pdf or whatever the final file format is?

**Comment by satishbabariya** [comment]
yeah.

**Comment by satishbabariya** [comment]
options like,
```go
const (
	CBR  = "cbr"
	CBZ  = "cbz"
	EPUB = "epub"
	PDF  = "pdf"
        IMG = "img"
)
```

**Comment by Girbons** [comment]
@satishbabariya  What do you think about something like 2 parameters like `--only-images` used alongside `--images-format`?

**Comment by satishbabariya** [comment]
@Girbons, that would be great,  also `--images-format` can have a default value if not given?
and `--only-images` will not create pdf's right?

**Comment by Girbons** [comment]
@satishbabariya  Just the images, no PDF.
As default Image format I was thininking about png.

**Comment by satishbabariya** [comment]
@Girbons :thumbsup:

**Comment by Girbons** [comment]
@satishbabariya if you want to try out this branch feel free to do it, would be nice to have a feedback!

I need to fix few things in the GUI then I will release the 0.15.

**Comment by satishbabariya** [comment]
@Girbons sure, though not working when passing -url flag with multiple or single urls
```bash
go run cmd/downloader/main.go -url=https://mangarock.com/manga/mrs-serie-100350535/chapter/mrs-chapter-100409200 -images-only
```

**Comment by satishbabariya** [comment]
@Girbons, wouldn't it better to download the images directly to the respective folder `comics/mangarock.com/Solo Leveling` rather than using temp dir

**Comment by Girbons** [comment]
> @Girbons, wouldn't it better to download the images directly to the respective folder comics/mangarock.com/Solo Leveling/Solo Leveling-Chapter 53/img1.png rather than using temp dir

Yes, its a good idea, I need to refactor that part.

>  the image will download every time (i think)

Yes, right now there aren't checks to see if there is already an image folder.
