### ISSUE TITLE
Mangadex no longer working

### ISSUE THREAD

**Issue by futurevessel** [Girbons/comics-downloader#45]
Just putting it here in the hopes that this great application hasn't been abandoned. Mangadex naturally no longer working after moving to a new host and address.

**Comment by Girbons** [comment]
Hi @futurevessel,

We are going to ship a fix soon!

**Comment by Girbons** [comment]
solved by [v0.19.1](https://github.com/Girbons/comics-downloader/commits/v0.19.1)
