### ISSUE TITLE
mangago.net support

### ISSUE THREAD

**Issue by paranoid73** [Girbons/comics-downloader#5]
Hello , 
can you add mangago.net support ,
example : http://www.mangago.me/read-manga/the_third_party/mf/iur_chapter-58/pg-1/

**Comment by Girbons** [comment]
I'm unable to reach this site.

**Comment by paranoid73** [comment]
> I'm unable to reach this site.

http://www.mangago.me now

**Comment by Girbons** [comment]
The problem with sites like this one is that they have cloudflare protection and I didn't find a library to bypass it

**Comment by llinaresvicent** [comment]
Hi! What do you think about this one?  [https://github.com/cardigann/go-cloudflare-scraper](https://github.com/cardigann/go-cloudflare-scraper)

**Comment by Girbons** [comment]
Hi @llinaresvicent,

go-cloudlfare-scraper seems to not be maintained anymore.
