### ISSUE TITLE
Language Filter

### ISSUE THREAD

**Issue by MrTyton** [Girbons/comics-downloader#50]
Can't seem to get the country/language filter working on mangadex.org. No matter what the input, always gives the error 'no chapters found'

ex url: https://mangadex.org/title/35064/i-m-a-villainous-daughter-so-i-m-going-to-keep-the-last-boss

ex countries tried: US, USA, English, En, en/US, en_US, Ru, Russia, Japan

**Comment by Girbons** [comment]
@MrTyton try to use the country in lowercase eg `gb`.

**Comment by turtletowerz** [comment]
Mangadex uses ISO 3166-1 languages codes, a list of them can be found [here](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). Just look in the left-most column and make sure it's lowercase when you put it into the command

**Comment by Girbons** [comment]
Thanks @turtletowerz, We should add this in the readme

**Comment by turtletowerz** [comment]
I'd be happy to create a PR for it. It's unfortunate they use this though because it's not as well known and took me forever to find!
