### ISSUE TITLE
Separate by comma

### ISSUE THREAD

**Issue by Arrowerse2001** [Girbons/comics-downloader#54]
Using multiple urls for https://www.comicextra.com doesn't download them. Need to have one url at a time.

**Comment by Girbons** [comment]
Hi @Arrowerse2001, 

Thanks for reporting, I'll check asap!

**Comment by Arrowerse2001** [comment]
Thanks, it's the windows gui it does it on.

**Comment by Girbons** [comment]
@Arrowerse2001 Released [v0.22.2](https://github.com/Girbons/comics-downloader/releases/tag/v0.22.2)
