### ISSUE TITLE
Mangatown download ERROR 0024

### ISSUE THREAD

**Issue by sydrawat** [Girbons/comics-downloader#55]
<img width="809" alt="Screenshot 2020-04-08 at 03 33 36" src="https://user-images.githubusercontent.com/22128987/78723914-f3ea1800-7949-11ea-8d0d-4995e8484616.png">

There seems to be an error (somewhat like 0024) and says GET from a particular URL has unsupported protocol scheme.

I've attached a screenshot of the same.

It says "downloading...", but after a few seconds, I get the error message.

**Comment by sydrawat** [comment]
Could it be a problem from mangatown's side?

**Comment by sydrawat** [comment]
Says "Couldn't perform GET request to [url](http://www.mangatown.com/manga/shingeki_no_kyojin/c128/1.html)"

<img width="911" alt="Screenshot 2020-04-08 at 12 11 35" src="https://user-images.githubusercontent.com/22128987/78752706-30d9fd00-7992-11ea-9d88-16a575a2f5dc.png">

**Comment by Girbons** [comment]
Hi @sydrawat,

It seems that the `http` protocol is missing while performing the GET request on the image URL, in the first attached screenshot there's `unsupported protocol scheme ""`.
So the error might be here https://github.com/Girbons/comics-downloader/blob/master/pkg/sites/mangatown.go#L41-L47.

**Comment by Girbons** [comment]
@sydrawat a new release will be available by the end of the week.

**Comment by Girbons** [comment]
@sydrawat Released [v0.22.2](https://github.com/Girbons/comics-downloader/releases/tag/v0.22.2)
