### ISSUE TITLE
SIGSEGV segmentation fault with runtime error : MANGATOWN

### ISSUE THREAD

**Issue by sydrawat** [Girbons/comics-downloader#57]
**Describe the bug**
Runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1375265]

**To Reproduce**
Running the cmd:
./comics-downloader -url=https://www.mangatown.com/manga/monster/v01/c001

**Expected behavior**
Manga to be downloaded successfully.

**Screenshots**
<img width="809" alt="Screenshot 2020-04-21 at 02 03 22" src="https://user-images.githubusercontent.com/22128987/79797643-3dd4f400-8375-11ea-8e7b-d4d9d5932cf9.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: v0.22.1
 - Type: cmd

**Comment by Girbons** [comment]
Hi @sydrawat thanks for reporting,
try with the latest release, there was a fix related to mangatown

**Comment by sydrawat** [comment]
Hi @Girbons it doesn't seem to be working with v0.22.2 as well. It throws a GET error.
<img width="799" alt="Screenshot 2020-04-21 at 12 39 27" src="https://user-images.githubusercontent.com/22128987/79836009-45c08280-83cd-11ea-86d8-ac30b259c52f.png">

**Comment by sydrawat** [comment]
I

> Hi @Girbons it doesn't seem to be working with v0.22.2 as well. It throws a GET error.
> <img alt="Screenshot 2020-04-21 at 12 39 27" width="799" src="https://user-images.githubusercontent.com/22128987/79836009-45c08280-83cd-11ea-86d8-ac30b259c52f.png">

It seems to be going to [v18/c162](https://www.mangatown.com/manga/monster/v18/c162/) instead of [v01/c001](https://www.mangatown.com/manga/monster/v01/c001/).

**Comment by Girbons** [comment]
@sydrawat so it is working using another chapter?

**Comment by sydrawat** [comment]
Nope. After updating to v0.22.2, the SIGSEGV errors are gone, but GET errors are still present.
And for some reason, the URL keeps redirecting to a different one everytime.

**This happens only with Mangatown**. Every other supported site works just fine. I tried downloading a couple of different mangas apart from monster as well(Mangatown), same problem: URL redirects to a different one and then GET error.

**Comment by Girbons** [comment]
I need to investigate on this

**Comment by Girbons** [comment]
Hey @sydrawat, 

sorry for the late response, the issue is caused by the pop-up image that needs to be closed.

**Comment by sydrawat** [comment]
Hey @Girbons! Thanks for the update. Do you mean the loading gif? Because I didn't get any pop-up image on the [URL](https://www.mangatown.com/manga/monster/v01/c001).

**Comment by Girbons** [comment]
When I tried to understand what was going on, a pop image was displayed at first.
Anyway I'll try to check again this weekend and see if I can solve this issue.

**Comment by Girbons** [comment]
@sydrawat Try to append a `/` at the end of the URL
