### ISSUE TITLE
comicextra -all flag is not using issueNumber on the output filename

### ISSUE THREAD

**Issue by jwhittaker** [Girbons/comics-downloader#58]
**Describe the bug**
The chapter (aka issues) are overwriting each other's output files. Every file is named the same `xyz.cbz` in the same directory.

The `issueNumber` is not being included in the output filename. This causes the next chapter's `.cbz` or `.pdf` file to override previously completed one because the destinations are always the same.

**To Reproduce**
```bash
./comic-dl -format cbz -all -url https://www.comicextra.com/comic/xyz
```

**Expected behavior**

I expected to have each chapter/issue as its own new file: xyz-001.cbz, xyz-002.cbz, xyz-003.cbz

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 5.3.0-46-generic x86_64
 - Version: v0.22.2
 - Type: CLI

**Additional context**

Renaming each `.cbz` manually in another shell before the next issue completes shows me it is correctly grabbing the next issue. The same thing happens when using `.pdf` as the output.

```bash
cd comics/www.comicextra.com/comic
mv xyz.cbz xyz-100.cbz
# wait manually to see the new file show up
mv xyz.cbz xyz-099.cbz
```

etc...

```bash
stat -c "%y %s %n" *
2020-04-21 21:09:01.471668081 +0000 23640516 xyz-098.cbz
2020-04-21 21:08:42.815279882 +0000 23423476 xyz-099.cbz
2020-04-21 21:08:23.302851654 +0000 37556936 xyz-100.cbz
```

**Comment by sydrawat** [comment]
Same issue with the `-all` flag in mangadex as well.

**Comment by Girbons** [comment]
@jwhittaker thanks for the report and for digging through

I'm going to do a release in the morning, I have discovered why this is happening.
