### ISSUE TITLE
Mangadex no longer working, the sequel

### ISSUE THREAD

**Issue by futurevessel** [Girbons/comics-downloader#63]
Had this exact problem a couple of months ago, but then it started working again after just a couple of hours which made me remove the issue, now it's been two days where I get this same error message: 'could not unmarshal chapter XXXXXXX: json: cannot unmarshal bool into Go struct field Chapter.long_strip of type int' on everything I try to download on Mangadex.

I use the following command: comics-downloader -format cbz <chapter>

Have tried using the 0.23.0 release as well as compile it myself from source

**Comment by Girbons** [comment]
Hi @futurevessel, 

Thanks for reporting this issue, I'm currently investigating.

**Comment by Girbons** [comment]
mangadex seems to be offline 😅

**Comment by futurevessel** [comment]
Heh, yes I just saw that, what are the odds !?

Anyway it seems that it's up again. Should probably have mentioned that I'm on Linux (Arch), anyway, thanks for looking into this and thanks for a great tool!

**Comment by Girbons** [comment]
There might still be an error in mangadex for some chapters. 

> Anyway it seems that it's up again. Should probably have mentioned that I'm on Linux (Arch), anyway, thanks for looking into this and thanks for a great tool!

Thank you!

**Comment by Girbons** [comment]
Solved in [v0.23.1](https://github.com/Girbons/comics-downloader/releases/tag/v0.23.1)
