### ISSUE TITLE
Installation issue Mac OS 

### ISSUE THREAD

**Issue by inglesuniversal** [Girbons/comics-downloader#65]
I'm new to GoLang, do I need to install Go on a Mac before running your script?

--> brew install golang

Thanks

**Comment by Girbons** [comment]
Hi @inglesuniversal, 

there's no need to have golang installed to run the scripts that you find here https://github.com/Girbons/comics-downloader#installing 😄.

**Comment by inglesuniversal** [comment]
Tried it on a Mac and Linux VM and worked like a charm. Thumbs up!

Is there a way to run the script in the remote server using PHP / Node or a simple web integration approach?

Thanks and STAY SAFE

**Comment by Girbons** [comment]
> Tried it on a Mac and Linux VM and worked like a charm. Thumbs up!

I'm glad that it worked!

> Is there a way to run the script in the remote server using PHP / Node or a simple web integration approach?

The tool is just a CLI at the moment so you'll have to execute it as command and get the exit code. By the way providing it as web service and expose an API is feasibile, I'll open a ticket and let this issue opened.

Thank you and stay safe!

**Comment by inglesuniversal** [comment]
WOW... That would be amazing... Making an API for the web. I often use it to allow some English Language Learners to compare the English from old to modern publications. Thanks for your amazing work!!!

**Comment by Girbons** [comment]
Soon I'll provide a containerized web version 😄 
>  often use it to allow some English Language Learners to compare the English from old to modern publications. Thanks for your amazing work!!!

That's really cool!! Thank you, I really appreciate that 🙏

**Comment by inglesuniversal** [comment]
By the way... first two sites listed have some issues not getting the content whenever is use the command -all ... it will skip some issues and the folder ends up with an empty PDF (about 826 bytes). Any clues?

**Comment by Girbons** [comment]
I’ll give a check this weekend, thanks for the report.

Could you please open a specific issue for this?

**Comment by Girbons** [comment]
closing in favor of #72
