### ISSUE TITLE
bug report: -all command gets only partial content

### ISSUE THREAD

**Issue by inglesuniversal** [Girbons/comics-downloader#66]
tested on linux vm and mac-os, the script refuses to download the complete contents from a given URL.

also, giving a full link causes the download stream to fail, so typically the best approach so far is to provide the base URL of the desired collection  https://domain.com/collection-name-year  

most of the files are generated and those unable to be processed end up with an empty PDF file (850 kb size)

sites tested on: 2 firsts suggested sites shown under installation and usage of the script.

STAY SAFE.

**Comment by Girbons** [comment]
the URL shown in usage might be changed, that's why fails

**Comment by hakuamesan** [comment]
I wasnt able to replicate this error.  Could you give the actual urls that you tried ?
