### ISSUE TITLE
SIGSEGV: segmentation violation while trying to download

### ISSUE THREAD

**Issue by hakuamesan** [Girbons/comics-downloader#68]
**Describe the bug**

Perhaps I'm running the command wrong, but I'm trying to download all the chapters of One Piece from Manga Reader.
Even so, I dont think it should SIG fault but rather fail gracefully.

**To Reproduce**
Run the cmd version 
./comics-downloader -all -url=https://www.mangareader.net/one-piece/

**Expected behavior**
Expected all the chapters of One Piece to be downloaded.

**Screenshots**

/web $ ./comics-downloader -all -url=https://www.mangareader.net/one-piece/
INFO[0000] Downloading...                                url="https://www.mangareader.net/one-piece/"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x78a14a]

goroutine 1 [running]:
github.com/anaskhan96/soup.findAllofem.func1(0x0, 0xc0001a2f20, 0x1, 0x1, 0x0)
	/home/samurai/go/pkg/mod/github.com/anaskhan96/soup@v1.1.1/soup.go:370 +0x8a
github.com/anaskhan96/soup.findAllofem(0x0, 0xc0001a2f20, 0x1, 0x1, 0x7cf500, 0x7f0dc0, 0xc0001a8001, 0x8)
	/home/samurai/go/pkg/mod/github.com/anaskhan96/soup@v1.1.1/soup.go:374 +0xf2
github.com/anaskhan96/soup.Root.FindAll(0x0, 0x0, 0x0, 0x8dbca0, 0xc0001a2f10, 0xc0001a2f20, 0x1, 0x1, 0x0, 0x0, ...)
	/home/samurai/go/pkg/mod/github.com/anaskhan96/soup@v1.1.1/soup.go:136 +0x6c
github.com/Girbons/comics-downloader/pkg/sites.(*Mangareader).RetrieveIssueLinks(0xb31598, 0x7fff49a4c50c, 0x26, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/web/comics-downloader-master/pkg/sites/mangareader.go:92 +0x2be
github.com/Girbons/comics-downloader/pkg/sites.LoadComicFromSource(0xc000077f08, 0x4, 0xc000077a18, 0x1, 0x1, 0x0)
	/web/comics-downloader-master/pkg/sites/loader.go:72 +0xe2
github.com/Girbons/comics-downloader/cmd/app.download(0xc000077f08, 0x30babb9a365a0e00)
	/web/comics-downloader-master/cmd/app/downloader.go:93 +0x619
github.com/Girbons/comics-downloader/cmd/app.Run(0xc000113f08)
	/web/comics-downloader-master/cmd/app/downloader.go:142 +0x89
main.main()
	/web/comics-downloader-master/cmd/downloader/main.go:83 +0x245

**Desktop (please complete the following information):**
 - OS: Debian Linux
 - Version Sid
 - Type : cmd

**Additional context**

**Comment by Girbons** [comment]
Hi @hakuamesan thanks for the report, the link you posted returns a 404 not found in my case.

**Comment by hakuamesan** [comment]
If the trailing / is removed, it doesnt return a 404. (or a seg fault!) 

However, it takes a really long time where it is just waiting at Downloading...    is there a Debug/trace option that I could turn on to check if anything is happening or if it is waiting / processing a large no of links ??   I'm new to go, so i'm just curious.

**Comment by Girbons** [comment]
> If the trailing / is removed, it doesnt return a 404. (or a seg fault!)

But that matters 😄 

>  is there a Debug/trace option that I could turn on to check if anything is happening or if it is waiting / processing a large no of links ?? I'm new to go, so i'm just curious.

Actually no, there is not debug option, you'll have to wait because what the script is doing is collecting all the chapters links and it will proceed with the download.

**Comment by hakuamesan** [comment]
true... I guess I will wait for the debug version :)

Thanks!
