### ISSUE TITLE
Error: This site is not supported

### ISSUE THREAD

**Issue by kavishgr** [Girbons/comics-downloader#79]
I ran the following command:

```
./comics-downloader-osx -url "https://readcomiconline.li/Comic/The-Action-Bible/TPB-1?id=123938"
```

**the result**:

```
ERRO[0001] This site is not supported
```

I'm not sure if I'm using the right syntax. Am I missing something ?

**Comment by Girbons** [comment]
Hi @kavishgr,

The command is fine, I see that the domain is changed from `.to` to `.li` as you see [here](https://github.com/Girbons/comics-downloader/blob/master/pkg/detector/detector.go#L9#L17).

I'm going to ship a fix or if you want to contribute, feel free, PRs are welcome :D

**Comment by kavishgr** [comment]
Done 👍

**Comment by Girbons** [comment]
Thanks @kavishgr, I'm preparing the new release!
