### ISSUE TITLE
Change behaviour of -output to not prepend any folders

### ISSUE THREAD

**Issue by mikebell** [Girbons/comics-downloader#89]
When I use the `-output` flag I expected the files to be downloaded into the directory specified.

```
-output=/mnt/media/$mydirectory
```

I get the following :

```
/mnt/media/$mydirectory/comics/$source/$name
```

The documentation doesn't mention this behaviour. Is there an option not to prepend with folders?

**Comment by Girbons** [comment]
Hi @mikebell, 

`comics/$source/$name` is the default folder structure that is being created and there's no way to avoid this by using an option.

> The documentation doesn't mention this behaviour

I will edit the README to mention this behaviour.

**Comment by Girbons** [comment]
Hey @mikebell,

After a while of thinking, I've decided to take into consideration your proposal, soon there will be a new release.
